# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029fe0e87158c160c6feb56171fe578b3903d571791bc8c4ee3851e9ad67508bc772d0de4d796c253bc776a1682649f616cdf2de19cd2deb29acde2ffcb73355

test:
  secret_key_base: df630ae9f1189b5a9f979036e80c4ea8a8d79b79ced8430488ea80fb861719c9bb587a69c61e6da9ed0215a8ab1e91799036c669a57b9d0f3469ce8227cf0776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
